# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.6.0'
git_version = '6b9e76d6fca74d5ddbf47049b9670120abaaf70f'
