#!/usr/bin/env python
# -*- coding:utf-8 -*-
# Copyright 2020 Huawei Technologies Co., Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================
"""
runtime api module
"""

RT_DEV_BINARY_MAGIC_PLAIN = 0xabceed50
RT_DEV_BINARY_MAGIC_PLAIN_AICPU = 0xabceed51
RT_DEV_BINARY_MAGIC_PLAIN_AIVEC = 0xabceed52
RT_DEV_BINARY_MAGIC_ELF = 0x43554245
RT_DEV_BINARY_MAGIC_ELF_AICPU = 0x41415243
RT_DEV_BINARY_MAGIC_ELF_AIVEC = 0x41415246
RT_DEV_BINARY_MAGIC_ELF_AICUBE = 0x41494343

MAGIC_MAP = {
    "RT_DEV_BINARY_MAGIC_ELF_AIVEC": RT_DEV_BINARY_MAGIC_ELF_AIVEC,
    "RT_DEV_BINARY_MAGIC_ELF_AIVECTOR": RT_DEV_BINARY_MAGIC_ELF_AIVEC,
    "RT_DEV_BINARY_MAGIC_ELF": RT_DEV_BINARY_MAGIC_ELF,
    "RT_DEV_BINARY_MAGIC_ELF_AICPU": RT_DEV_BINARY_MAGIC_ELF_AICPU,
    "RT_DEV_BINARY_MAGIC_PLAIN_AIVEC": RT_DEV_BINARY_MAGIC_PLAIN_AIVEC,
    "RT_DEV_BINARY_MAGIC_PLAIN_AICPU": RT_DEV_BINARY_MAGIC_PLAIN_AICPU,
    "RT_DEV_BINARY_MAGIC_PLAIN": RT_DEV_BINARY_MAGIC_PLAIN,
    "RT_DEV_BINARY_MAGIC_ELF_AICUBE": RT_DEV_BINARY_MAGIC_ELF_AICUBE
}

RT_MEMORY_TYPE = {
    "RT_MEMORY_DEFAULT": 0,
    "RT_MEMORY_HBM": 2,
    "RT_MEMORY_DDR": 4,
    "RT_MEMORY_SPM": 8,
    "RT_MEMORY_P2P_HBM": 0x10,
    "RT_MEMORY_P2P_DDR": 0x11,
    "RT_MEMORY_DDR_NC": 0x20,
    "RT_MEMORY_TS_4G": 0x40,
    "RT_MEMORY_TS": 0x80,
    "RT_MEMORY_RESERVED": 0x100,
    "RT_MEMORY_L1": 0x10000,
    "RT_MEMORY_L2": 0x20000
}

RT_MODULE_TYPE = {
    "MODULE_TYPE_SYSTEM": 0,
    "MODULE_TYPE_AICPU": 1,
    "MODULE_TYPE_CCPU": 2,
    "MODULE_TYPE_DCPU": 3,
    "MODULE_TYPE_AICORE": 4,
    "MODULE_TYPE_TSCPU": 5,
    "MODULE_TYPE_PCIE": 6
}

RT_INFO_TYPE = {
    "INFO_TYPE_ENV": 0,
    "INFO_TYPE_VERSION": 1,
    "INFO_TYPE_MASTERID": 2,
    "INFO_TYPE_CORE_NUM": 3,
    "INFO_TYPE_OS_SCHED": 4,
    "INFO_TYPE_IN_USED": 5,
    "INFO_TYPE_ERROR_MAP": 6,
    "INFO_TYPE_OCCUPY": 7,
    "INFO_TYPE_ID": 8,
    "INFO_TYPE_IP": 9,
    "INFO_TYPE_ENDIAN": 10
}

RT_MEMORY_POLICY = {
    "RT_MEMORY_POLICY_NONE": 0x0,
    "RT_MEMORY_POLICY_HUGE_PAGE_FIRST": 0x400,
    "RT_MEMORY_POLICY_HUGE_PAGE_ONLY": 0x800,
    "RT_MEMORY_POLICY_DEFAULT_PAGE_ONLY": 0x1000,
    "RT_MEMORY_POLICY_HUGE_PAGE_FIRST_P2P": 0x2000,
    "RT_MEMORY_POLICY_HUGE_PAGE_ONLY_P2P": 0x4000,
    "RT_MEMORY_POLICY_DEFAULT_PAGE_ONLY_P2P": 0x8000
}

RT_MEMCPY_KIND = {
    "RT_MEMCPY_HOST_TO_HOST": 0,
    "RT_MEMCPY_HOST_TO_DEVICE": 1,
    "RT_MEMCPY_DEVICE_TO_HOST": 2,
    "RT_MEMCPY_DEVICE_TO_DEVICE": 3,
    "RT_MEMCPY_MANAGED": 4,
    "RT_MEMCPY_ADDR_DEVICE_TO_DEVICE": 5,
    "RT_MEMCPY_HOST_TO_DEVICE_EX": 6,
    "RT_MEMCPY_DEVICE_TO_HOST_EX": 7,
    "RT_MEMCPY_RESERVED": 8
}

MEMORY_INFO_TYPE = {
    "RT_MEMORYINFO_DDR": 0,
    "RT_MEMORYINFO_HBM": 1,
    "RT_MEMORYINFO_DDR_HUGE": 2,
    "RT_MEMORYINFO_DDR_NORMAL": 3,
    "RT_MEMORYINFO_HBM_HUGE": 4,
    "RT_MEMORYINFO_HBM_NORMAL": 5,
    "RT_MEMORYINFO_DDR_P2P_HUGE": 6,
    "RT_MEMORYINFO_DDR_P2P_NORMAL": 7,
    "RT_MEMORYINFO_HBM_P2P_HUGE": 8,
    "RT_MEMORYINFO_HBM_P2P_NORMAL": 9,
}

RT_CONTEXT_MODE = {
    "RT_CTX_NORMAL_MODE": 0,
    "RT_CTX_GEN_MODE": 1
}

RT_KERNEL_FLAGS = {
    "default": 0x00,
    "convert": 0x01,
    "dumpflag": 0x02
}

RT_FUNC_MODE_DICT = {
    "FUNC_MODE_NORMAL": 0,
    "FUNC_MODE_PCTRACE_USERPROFILE_RECORDLOOP": 1,
    "FUNC_MODE_PCTRACE_USERPROFILE_SKIPLOOP": 2,
    "FUNC_MODE_PCTRACE_CYCLECNT_RECORDLOOP": 3,
    "FUNC_MODE_PCTRACE_CYCLECNT_SKIPLOOP": 4,
    "FUNC_MODE_BUTT": 5,
}

RT_ENV_TYPE = {
    0: "FPGA",
    1: "EMU",
    2: "ESL"
}

RT_ERROR_TYPE_DICT = {
    0x00000000: "UNKNOWN",
    0x00010000: "DEVICE",
    0x00020000: "DRV",
    0x00030000: "STREAM",
    0x00040000: "MODEL",
    0x00050000: "EVENT",
    0x00060000: "NOTIFY",
    0x00070000: "CONTEXT",
    0x00080000: "KERNEL",
    0x00090000: "PROGRAM",
    0x000a0000: "MODULE",
    0x000b0000: "INSTANCE",
    0x000c0000: "API",
    0x000d0000: "DATADUMP",
    0x000e0000: "PROF",
    0x000f0000: "PCTRACE",
    0x00100000: "TASK",
    0x00110000: "COMMON",
    0x00120000: "DEBUG",
    0x00130000: "ENGINE",
    0x00140000: "LABEL",
    0x00150000: "TSFW",
    0x00160000: "SUBSCRIBE",
    0x00170000: "GROUP",
    0x00FF0000: "RESERVED"
}

RT_ERROR_CODE_DICT = {
    0x00000000: ("RT_ERROR_UNKNOWN_UNKNOWN0",
                 "RT_ERROR_UNKNOWN_UNKNOWN1",
                 "RT_ERROR_UNKNOWN_UNKNOWN2",
                 "RT_ERROR_UNKNOWN_UNKNOWN3",
                 "RT_ERROR_UNKNOWN_UNKNOWN4",
                 "RT_ERROR_UNKNOWN_UNKNOWN5",
                 "RT_ERROR_UNKNOWN_UNKNOWN6",
                 "RT_ERROR_UNKNOWN_UNKNOWN7",
                 "RT_ERROR_UNKNOWN_UNKNOWN8",
                 "RT_ERROR_UNKNOWN_UNKNOWN9",
                 "RT_ERROR_UNKNOWN_UNKNOWNA",
                 "RT_ERROR_UNKNOWN_UNKNOWNB",
                 "RT_ERROR_UNKNOWN_UNKNOWNC",
                 "RT_ERROR_UNKNOWN_UNKNOWND",
                 "RT_ERROR_UNKNOWN_UNKNOWNE",
                 "RT_ERROR_UNKNOWN_UNKNOWNF",),
    0x00010000: ("RT_ERROR_DEVICE_BASE",
                 "RT_ERROR_DEVICE_NULL",
                 "RT_ERROR_DEVICE_NEW",
                 "RT_ERROR_DEVICE_ID",
                 "RT_ERROR_DEVICE_CHIPTYPE",
                 "RT_ERROR_DEVICE_DEPLOY",
                 "RT_ERROR_DEVICE_RETAIN",
                 "RT_ERROR_DEVICE_PLATFORM",
                 "RT_ERROR_DEVICE_LOADER",
                 "RT_ERROR_DEVICE_LIMIT",
                 "RT_ERROR_DEVICE_PROC_HANG_OUT",
                 "RT_ERROR_DEVICE_POWER_UP_FAIL",
                 "RT_ERROR_DEVICE_POWER_DOWN_FAIL",
                 "RT_ERROR_DEVICE_INVALID",),
    0x00020000: ("RT_ERROR_DRV_BASE",
                 "RT_ERROR_DRV_NULL",
                 "RT_ERROR_DRV_NEW",
                 "RT_ERROR_DRV_MEMORY",
                 "RT_ERROR_DRV_INPUT",
                 "RT_ERROR_DRV_PTRNULL",
                 "RT_ERROR_DRV_OPEN_AICPU",
                 "RT_ERROR_DRV_CLOSE_AICPU",
                 "RT_ERROR_DRV_SYM_AICPU",
                 "RT_ERROR_DRV_OPEN_TSD",
                 "RT_ERROR_DRV_CLOSE_TSD",
                 "RT_ERROR_DRV_SYM_TSD",
                 "RT_ERROR_DRV_SOURCE",
                 "RT_ERROR_DRV_REPORT",
                 "RT_ERROR_DRV_COMMAND",
                 "RT_ERROR_DRV_OCCUPY",
                 "RT_ERROR_DRV_ERR",),
    0x00030000: ("RT_ERROR_STREAM_BASE",
                 "RT_ERROR_STREAM_NULL",
                 "RT_ERROR_STREAM_NEW",
                 "RT_ERROR_STREAM_CONTEXT",
                 "RT_ERROR_STREAM_INVALID",
                 "RT_ERROR_STREAM_MODEL",
                 "RT_ERROR_STREAM_FUSION",
                 "RT_ERROR_STREAM_FULL",
                 "RT_ERROR_STREAM_EMPTY",
                 "RT_ERROR_STREAM_NOT_COMPLETE",
                 "RT_ERROR_STREAM_SYNC",
                 "RT_ERROR_STREAM_NO_CB_REG",
                 "RT_ERROR_STREAM_DUPLICATE",
                 "RT_ERROR_STREAM_NOT_EXIST",
                 "RT_ERROR_SQ_NO_EXIST_SQ_TO_REUSE",
                 "RT_ERROR_SQID_FULL"),
    0x00040000: ("RT_ERROR_MODEL_BASE",
                 "RT_ERROR_MODEL_NULL",
                 "RT_ERROR_MODEL_NEW",
                 "RT_ERROR_MODEL_CONTEXT",
                 "RT_ERROR_MODEL_ENDGRAPH",
                 "RT_ERROR_MODEL_STREAM",
                 "RT_ERROR_MODEL_EXCUTOR",
                 "RT_ERROR_MODEL_SETUP",
                 "RT_ERROR_MODEL_ID",
                 "RT_ERROR_MODEL_EXE_FAILED",
                 "RT_ERROR_END_OF_SEQUENCE",),
    0x00050000: ("RT_ERROR_EVENT_BASE",
                 "RT_ERROR_EVENT_NULL",
                 "RT_ERROR_EVENT_NEW",
                 "RT_ERROR_EVENT_RECORDER_NULL",
                 "RT_ERROR_EVENT_TIMESTAMP_INVALID",
                 "RT_ERROR_EVENT_TIMESTAMP_REVERSAL",
                 "RT_ERROR_EVENT_NOT_COMPLETE",),
    0x00060000: ("RT_ERROR_NOTIFY_BASE",
                 "RT_ERROR_NOTIFY_NULL",
                 "RT_ERROR_NOTIFY_NEW",
                 "RT_ERROR_NOTIFY_TYPE",
                 "RT_ERROR_NOTIFY_NOT_COMPLETE",),
    0x00070000: ("RT_ERROR_CONTEXT_BASE",
                 "RT_ERROR_CONTEXT_NULL",
                 "RT_ERROR_CONTEXT_NEW",
                 "RT_ERROR_CONTEXT_DEL",
                 "RT_ERROR_CONTEXT_DEFAULT_STREAM_NULL",
                 "RT_ERROR_CONTEXT_ONLINE_STREAM_NULL",),
    0x00080000: ("RT_ERROR_KERNEL_BASE",
                 "RT_ERROR_KERNEL_NULL",
                 "RT_ERROR_KERNEL_NEW",
                 "RT_ERROR_KERNEL_LOOKUP",
                 "RT_ERROR_KERNEL_NAME",
                 "RT_ERROR_KERNEL_TYPE",
                 "RT_ERROR_KERNEL_OFFSET",
                 "RT_ERROR_KERNEL_DUPLICATE",
                 "RT_ERROR_KERNEL_UNREGISTERING",),
    0x00090000: ("RT_ERROR_PROGRAM_BASE",
                 "RT_ERROR_PROGRAM_NULL",
                 "RT_ERROR_PROGRAM_NEW",
                 "RT_ERROR_PROGRAM_DATA",
                 "RT_ERROR_PROGRAM_SIZE",
                 "RT_ERROR_PROGRAM_MEM_TYPE",
                 "RT_ERROR_PROGRAM_MACHINE_TYPE",
                 "RT_ERROR_PROGRAM_USEOUT",),
    0x000a0000: ("RT_ERROR_MODULE_BASE",
                 "RT_ERROR_MODULE_NULL",
                 "RT_ERROR_MODULE_NEW",),
    0x000b0000: ("RT_ERROR_INSTANCE_BASE",
                 "RT_ERROR_INSTANCE_NULL",
                 "RT_ERROR_INSTANCE_NEW",
                 "RT_ERROR_INSTANCE_VERSION",),
    0x000c0000: ("RT_ERROR_API_BASE",
                 "RT_ERROR_API_NULL",
                 "RT_ERROR_API_NEW",),
    0x000d0000: ("RT_ERROR_DATADUMP_BASE",
                 "RT_ERROR_DATADUMP_NULL",
                 "RT_ERROR_DATADUMP_NEW",
                 "RT_ERROR_DATADUMP_TIME",
                 "RT_ERROR_DATADUMP_FILE",
                 "RT_ERROR_DATADUMP_ADDRESS",
                 "RT_ERROR_DATADUMP_LOAD_FAILED",
                 "RT_ERROR_DUMP_ADDR_SET_FAILED",),
    0x000e0000: ("RT_ERROR_PROF_BASE",
                 "RT_ERROR_PROF_NULL",
                 "RT_ERROR_PROF_NEW",
                 "RT_ERROR_PROF_START",
                 "RT_ERROR_PROF_DEVICE_MEM",
                 "RT_ERROR_PROF_HOST_MEM",
                 "RT_ERROR_PROF_SET_DIR",
                 "RT_ERROR_PROF_OPER",
                 "RT_ERROR_PROF_FULL",
                 "RT_ERROR_PROF_NAME",),
    0x000f0000: ("RT_ERROR_PCTRACE_BASE",
                 "RT_ERROR_PCTRACE_NULL",
                 "RT_ERROR_PCTRACE_NEW",
                 "RT_ERROR_PCTRACE_TIME",
                 "RT_ERROR_PCTRACE_FILE",),
    0x00100000: ("RT_ERROR_TASK_BASE",
                 "RT_ERROR_TASK_NULL",
                 "RT_ERROR_TASK_NEW",
                 "RT_ERROR_TASK_TYPE",
                 "RT_ERROR_TASK_ALLOCATOR",),
    0x00110000: ("RT_ERROR_COMMON_BASE",
                 "RT_ERROR_INVALID_VALUE",
                 "RT_ERROR_MEMORY_ADDRESS_UNALIGNED",
                 "RT_ERROR_SEC_HANDLE",
                 "RT_ERROR_OS_HANDLE",
                 "RT_ERROR_MUTEX_LOCK",
                 "RT_ERROR_MUTEX_UNLOCK",
                 "RT_ERROR_CALLOC",
                 "RT_ERROR_POOL_RESOURCE",
                 "RT_ERROR_TRANS_ARGS",
                 "RT_ERROR_METADATA",
                 "RT_ERROR_LOST_HEARTBEAT",
                 "RT_ERROR_REPORT_TIMEOUT",
                 "RT_ERROR_FEATURE_NOT_SUPPORT",
                 "RT_ERROR_MEMORY_ALLOCATION",
                 "RT_ERROR_MEMORY_FREE",
                 "RT_ERROR_INVALID_MEMORY_TYPE",),
    0x00120000: ("RT_ERROR_DEBUG_BASE",
                 "RT_ERROR_DEBUG_NULL",
                 "RT_ERROR_DEBUG_NEW",
                 "RT_ERROR_DEBUG_SIGNAL",
                 "RT_ERROR_DEBUG_OPEN",
                 "RT_ERROR_DEBUG_WRITE",
                 "RT_ERROR_DEBUG_REGISTER_FAILED",
                 "RT_ERROR_DEBUG_UNREGISTER_FAILED",),
    0x00130000: ("RT_ERROR_ENGINE_BASE",
                 "RT_ERROR_ENGINE_NULL",
                 "RT_ERROR_ENGINE_NEW",
                 "RT_ERROR_ENGINE_THREAD",),
    0x00140000: ("RT_ERROR_LABEL_BASE",
                 "RT_ERROR_LABEL_NULL",
                 "RT_ERROR_LABEL_NEW",
                 "RT_ERROR_LABEL_CONTEXT",
                 "RT_ERROR_LABEL_STREAM",
                 "RT_ERROR_LABEL_MODEL",
                 "RT_ERROR_LABEL_ALLOCATOR",
                 "RT_ERROR_LABEL_FREE",
                 "RT_ERROR_LABEL_SET",
                 "RT_ERROR_LABEL_ID",),
    0x00150000: ("RT_ERROR_TSFW_BASE",
                 "RT_ERROR_TSFW_UNKNOWN",
                 "RT_ERROR_TSFW_NULL_PTR",
                 "RT_ERROR_TSFW_ILLEGAL_AI_CORE_ID",
                 "RT_ERROR_TSFW_ILLEGAL_PARAM",
                 "RT_ERROR_TSFW_TASK_CMD_QUEUE_FULL",
                 "RT_ERROR_TSFW_TASK_CMD_QUEUE_EMPTY",
                 "RT_ERROR_TSFW_TASK_REPORT_QUEUE_FULL",
                 "RT_ERROR_TSFW_TASK_REPORT_QUEUE_EMPTY",
                 "RT_ERROR_TSFW_TASK_NODE_BUFF_ALL_OCCUPYED",
                 "RT_ERROR_TSFW_TASK_NODE_BUFF_ALL_FREED",
                 "RT_ERROR_TSFW_L2_MEM_INSUFFICIENT_SPACE",
                 "RT_ERROR_TSFW_L2_MALLOC_FAILED",
                 "RT_ERROR_TSFW_DMA_CHANNEL_ALL_OCCUPYED",
                 "RT_ERROR_TSFW_MEMCPY_OP_FAILED",
                 "RT_ERROR_TSFW_BS_SLOT_ALL_OCCUPYED",
                 "RT_ERROR_TSFW_TBS_SLOT_REPEAT_FREE",
                 "RT_ERROR_TSFW_PRIORITY_TASK_LIST_FULL",
                 "RT_ERROR_TSFW_PRIORITY_TASK_LIST_EMPTY",
                 "RT_ERROR_TSFW_NO_STREAM_LIST_NEED_TO_BE_PROCESSED",
                 "RT_ERROR_TSFW_REPEAT_MARK_STREAM_NEED_SERVICE",
                 "RT_ERROR_TSFW_SYS_DMA_CHANNEL_ALL_OCCUPAPYED",
                 "RT_ERROR_TSFW_NO_HBML2TASKNODE_FOUND",
                 "RT_ERROR_TSFW_SQNODE_NODE_SLOT_ALL_OCCUPAPYED",
                 "RT_ERROR_TSFW_CQNODE_NODE_SLOT_ALL_OCCUPAPYED",
                 "RT_ERROR_TSFW_SQNODE_NOT_ENOUGH",
                 "RT_ERROR_TSFW_SQNODE_SLOT_REPEAT_FREE",
                 "RT_ERROR_TSFW_CQNODE_SLOT_REPEAT_FREE",
                 "RT_ERROR_TSFW_CQ_REPORT_FAILED",
                 "RT_ERROR_TSFW_SYS_DMA_RESET_SUCCESS",
                 "RT_ERROR_TSFW_SYS_DMA_RESET_FAILED",
                 "RT_ERROR_TSFW_SYS_DMA_TRNSFER_FAILED",
                 "RT_ERROR_TSFW_SYS_DMA_MEMADDRALIGN_FAILED",
                 "RT_ERROR_TSFW_SYS_DMA_ERROR_QUEUE_FULL",
                 "RT_ERROR_TSFW_SYS_DMA_ERROR_QUEUE_EMPTY",
                 "RT_ERROR_TSFW_TIMER_EVENT_FULL",
                 "RT_ERROR_TSFW_TASK_L2_DESC_ENTRY_NOT_ENOUGH",
                 "RT_ERROR_TSFW_AICORE_TIMEOUT",
                 "RT_ERROR_TSFW_AICORE_EXCEPTION",
                 "RT_ERROR_TSFW_AICORE_TRAP_EXCEPTION",
                 "RT_ERROR_TSFW_AICPU_TIMEOUT",
                 "RT_ERROR_TSFW_SDMA_L2_TO_DDR_MALLOC_FAIL",
                 "RT_ERROR_TSFW_AICPU_EXCEPTION",
                 "RT_ERROR_TSFW_AICPU_DATADUMP_RSP_ERR",
                 "RT_ERROR_TSFW_AICPU_MODEL_RSP_ERR",
                 "RT_ERROR_TSFW_REPEAT_ACTIVE_MODEL_STREAM",
                 "RT_ERROR_TSFW_REPEAT_NOTIFY_WAIT",
                 "RT_ERROR_TSFW_DEBUG_INVALID_SQCQ",
                 "RT_ERROR_TSFW_DEBUG_WRONG_COMMAND_TYPE",
                 "RT_ERROR_TSFW_DEBUG_CMD_PROCESS",
                 "RT_ERROR_TSFW_DEBUG_INVALID_DEVICE_STATUS",
                 "RT_ERROR_TSFW_DEBUG_NOT_IN_DEBUG_STATUS",
                 "RT_ERROR_TSFW_DEBUG_INVALID_TASK_STATUS",
                 "RT_ERROR_TSFW_DEBUG_TASK_EMPTY",
                 "RT_ERROR_TSFW_DEBUG_TASK_FULL",
                 "RT_ERROR_TSFW_DEBUG_TASK_NOT_EXIST",
                 "RT_ERROR_TSFW_DEBUG_AI_CORE_FULL",
                 "RT_ERROR_TSFW_DEBUG_AI_CORE_NOT_EXIST",
                 "RT_ERROR_TSFW_DEBUG_AI_CORE_EXCEPTION",
                 "RT_ERROR_TSFW_DEBUG_AI_CORE_TIMEOUT",
                 "RT_ERROR_TSFW_DEBUG_BREAKPOINT_FULL",
                 "RT_ERROR_TSFW_DEBUG_READ_ERROR",
                 "RT_ERROR_TSFW_DEBUG_WRITE_FAIL",
                 "RT_ERROR_TSFW_QUEUE_FULL",
                 "RT_ERROR_TSFW_QUEUE_EMPTY",
                 "RT_ERROR_TSFW_QUEUE_ALLOC_MEM_FAIL",
                 "RT_ERROR_TSFW_QUEUE_DATA_SIZE_UNMATCH",
                 "RT_ERROR_TSFW_PCIE_DMA_INVLD_CPY_TYPE",
                 "RT_ERROR_TSFW_INVLD_CPY_DIR",
                 "RT_ERROR_TSFW_PCIE_DMA_INVLD_CQ_DES",
                 "RT_ERROR_TSFW_PCIE_DMA_CPY_ERR",
                 "RT_ERROR_TSFW_PCIE_DMA_LNK_CHN_BUSY",
                 "RT_ERROR_TSFW_PROFILE_BUFF_FULL",
                 "RT_ERROR_TSFW_PROFILE_MODE_CONFLICT",
                 "RT_ERROR_TSFW_PROFILE_OTHER_PID_ON",
                 "RT_ERROR_TSFW_SCHD_AIC_TASK_PRELOAD_FAILED",
                 "RT_ERROR_TSFW_TSCPU_CLOSE_FAILED",
                 "RT_ERROR_TSFW_EXPECT_FAIL",
                 "RT_ERROR_TSFW_REPEAT_MODEL_STREAM",
                 "RT_ERROR_TSFW_STREAM_MODEL_UNBIND",
                 "RT_ERROR_TSFW_MODEL_EXE_FAILED",
                 "RT_ERROR_TSFW_IPC_SEND_FAILED",
                 "RT_ERROR_TSFW_IPC_PROC_REG_FAILED",
                 "RT_ERROR_TSFW_STREAM_FULL",
                 "RT_ERROR_TSFW_END_OF_SEQUENCE",
                 "RT_ERROR_TSFW_SWITCH_STREAM_LABEL",
                 "RT_ERROR_TSFW_TRANS_SQE_FAIL",
                 "RT_ERROR_TSFW_RESERVED",),
    0x00160000: ("RT_ERROR_SUBSCRIBE_BASE",
                 "RT_ERROR_SUBSCRIBE_NULL",
                 "RT_ERROR_SUBSCRIBE_NEW",
                 "RT_ERROR_SUBSCRIBE_STREAM",
                 "RT_ERROR_SUBSCRIBE_THREAD",
                 "RT_ERROR_SUBSCRIBE_GROUP",),
    0x00170000: ("RT_ERROR_GROUP_BASE",
                 "RT_ERROR_GROUP_NOT_SET",
                 "RT_ERROR_GROUP_NOT_CREATE",),
    0x00FF0000: ("RT_ERROR_RESERVED",),
}
