tensorflow_config:
    # 基本参数
    data_url: /home/imagenet_TF/
    epoches: 1
    epochs_between_evals: 1
    batch_size: 32
    log_dir: ./ckpt

    # 1p参数
    mode_1p: train     # train、evaluate、train_and_evaluate三种模式
    max_train_steps_1p: 100
    iterations_per_loop_1p: 10
    display_every: 10
    log_name_1p: densenet121_1p.log

    # 8p参数
    mode_8p: train_and_evaluate   # train、evaluate、train_and_evaluate三种模式
    iterations_per_loop_8p: 1000
    lr: 0.1
    log_name_8p: densenet121_8p.log

    # 仅多机执行需要配置: ip1:卡数量1,ip2:卡数量2
    mpirun_ip: 90.90.176.154:8,90.90.176.54:8

    # docker 镜像名称:版本号
    docker_image: c73:b02

    # 指定 device id, 多个 id 使用空格分隔, 数量需与 rank_size 相同
    device_group_1p: 0
    device_group_2p: 0 1
    device_group_4p: 0 1 2 3
    
pytorch_config:
    # 基本参数
    data_url: /home/imagenet/
    
    epoches: 90
    # 1p 参数为256  2p 512 4p 1024 8p为2048 
    batch_size: 256
    
    # 默认参数1p 0.1 2p 0.2 4p 0.4 8p 0.8
    lr: 0.1
    
    seed: 49
    
    # 单P指定卡 默认0卡
    device_single: 0
    
    # 2p 4p 8p 修改 2p可选 1，2或2，3 两两相连 4p 可选'0,1,2,3'或'1,2,3,4'规则同2p   8p默认为'0,1,2,3,4,5,6,7'
    device_group_multi: '0,1,2,3,4,5,6,7' 
    # docker 镜像名称:版本号
    docker_image: c73:b021
