pytorch_config:
    # 基本参数
    data_url: /home/imagenet/
    
    epoches: 90
    # 1p 参数为512 2p 1024 4p 2048 8p为4096
    batch_size: 512
    
    seed: 49
    
    # 默认参数1p 0.4 2p 0.8 4p 1.6 8p 3.2
    lr: 0.4
    
    #单P指定 卡 默认0卡
    device: 0
    
    # 2p 4p 8p 修改 2p可选 1，2或2，3 两两相连 4p 可选'0,1,2,3'或'1,2,3,4'规则同2p   8p默认为'0,1,2,3,4,5,6,7'
    device_group: '0,1,2,3,4,5,6,7'
    # docker 镜像名称:版本号
    docker_image: c73:b021
