tensorflow_config:
    # 基本参数
    max_steps: 1000
    data_url: /home/imagenet_TF/
    epoches: 1

    # 训练(train) 或 评测(evaluate)
    mode: train
    batch_size: 256
    #仅在 mode 为 evaluate 时用到
    ckpt_path: /opt/0908/benchmark-benchmark_Alpha/train/result/tf_mobilenet/trainingJob_20200905171017/0/results/model.ckpt-123125

    # 仅多机执行需要配置: ip1:卡数量1,ip2:卡数量2
    mpirun_ip: 90.90.176.152:8,90.90.176.154:8

    # docker 镜像名称:版本号
    docker_image: c73:b021

    # 指定 device id, 多个 id 使用空格分隔, 数量需与 rank_size 相同
    device_group_1p: 0
    device_group_2p: 0 1
    device_group_4p: 0 1 2 3    
    
    profiling_mode: false
    profiling_options: training_trace
    fp_point: L2Loss
    bp_point: gradients/AddN_30
    aicpu_profiling_mode: false


pytorch_config:
    # 基本参数
    data_url: /home/imagenet/
    
    epoches: 600
    
    # 单p默认512 2p 1024 4p 2048  8p默认4096
    batch_size: 512
    
    # 默认参数1p 0.05 2p 0.1 4p 0.2 8p 0.4
    lr: 0.05
    
    seed: 123456
    device_single: 'npu:0' 
    # 指定2p 4p 8p卡 2p可选'0,1' 4p可选'0,1,2,3' 8p为'0,1,2,3,4,5,6,7'
    device_group_mutli: '0,1,2,3'
   
    # docker 镜像名称:版本号
    docker_image: c73:b021
