tensorflow_config:
    # 基本参数
    max_steps: 1000
    data_url: /home/imagenet_TF
    epoches: 1
    epochs_between_evals: 1
    mode: train
    batch_size: 32
    
    # 仅多机执行需要配置: ip1:卡数量1,ip2:卡数量2
    mpirun_ip: 90.90.176.154:8,90.90.176.54:8

    # docker 镜像名称:版本号
    docker_image: mpirun3:latest


    # 1. 指定 device id, 多个 id 使用空格分隔, 数量需与 rank_size 相同
    # 2. 仅在小于 8p 时生效
    # 3. 若不使用该配置, 请使用在行首添加'#'注释的方法将其关闭
    # device_group: 0 1 2 3
    device_group_1p: 0
    device_group_2p: 0 1
    device_group_4p: 0 1 2 3
